baseurl = "/"
theme = "docs-developer-hugo-theme"
copyright = ""
defaultContentLanguage = "en-us"
destination = "public"
enableEmoji = true
enableRobotsTXT = true
languageCode = "en-us"
metaDataFormat = "yaml"
paginate = 10
pluralizeListTitles = false
relativeURLs = false
disablePathToLower = false
uglyURLs = false
smartDashes = true
title = "Rackspace Developer Center"
[markup]
defaultMarkdownHandler = "goldmark"
[markup.asciidocExt]
    backend = "html5"
    docType = "article"
    extensions = []
    failureLevel = "fatal"
    noHeaderOrFooter = true
    safeMode = "unsafe"
    sectionNumbers = false
    trace = false
    verbose = true
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]
  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ""
    footnoteReturnLinkContents = ""
    fractions = true
    hrefTargetBlank = false
    latexDashes = true
    nofollowLinks = false
    noreferrerLinks = false
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2


[permalinks]
    blog = "/blog/:slug"
    categories = "/blog/categories/:slug"
    author = "/blog/authors/:slug"

[[menu.docs]]
    name = "Welcome"
    weight = 1

[[menu.footer]]
    name = "Developer Center"
    parent = "Developer Network"
    url = "https://docs.rackspace.com"
    weight = 1
[[menu.footer]]
    name = "API Documentation and User Guides"
    parent = "Developer Network"
    url = "https://docs.rackspace.com/docs"
    weight = 2
[[menu.footer]]
    name = "SDKs"
    parent = "Developer Network"
    url = "https://docs.rackspace.com/sdks/python/"
    weight = 3
[[menu.footer]]
    name = "Rackspace How-To"
    parent = "Developer Network"
    url = "https://support.rackspace.com/how-to/"
    weight = 4
[[menu.footer]]
    name = "Technical Blog"
    parent = "Blogs"
    url = "https://docs.rackspace.com/blog"
    weight = 5
[[menu.footer]]
    name = "Rackspace Blog"
    parent = "Blogs"
    url = "https://www.rackspace.com/blog"
    weight = 6
[[menu.footer]]
    name = "Solve: Thought Leadership"
    parent = "Blogs"
    url = "https://www.rackspace.com/solve"
    weight = 7
[[menu.footer]]
    name = "Customer Stories"
    parent = "Other Information"
    url = "https://www.rackspace.com/customer-stories"
    weight = 8
[[menu.footer]]
    name = "Events"
    parent = "Other Information"
    url = "https://www.rackspace.com/events"
    weight = 9
[[menu.footer]]
    name = "Programs"
    parent = "Other Information"
    url = "https://www.rackspace.com/responsibility"
    weight = 10
[[menu.footer]]
    name = "Careers"
    parent = "Other Information"
    url = "https://jobs.jobvite.com/rackspace/"
    weight = 11
[[menu.footer]]
    name = "Style Guide for Technical Content"
    parent = "Other Information"
    url = "https://docs.rackspace.com/docs/style-guide/"
    weight = 12

[[menu.main]]
    identifier = "developer_home"
    name = "Developer Home"
    url = "https://docs.rackspace.com"
    weight = 1
[[menu.main]]
    identifier = "developer_documentation"
    name = "Developer Documentation"
    url = "https://docs.rackspace.com/docs"
    weight = 2
[[menu.main]]
    identifier = "blogs"
    name = "Blogs"
    url = "#"
    post = ""
    weight = 3
    [[menu.main]]
        identifier = "technical-blog"
        name ="Technical Blog"
        url ="https://docs.rackspace.com/blog"
        weight = 1
        parent = "blogs"
    [[menu.main]]
        identifier = "rackspace-blog"
        name = "Rackspace Blog"
        url = "https://www.rackspace.com/blog"
        weight = 2
        parent = "blogs"
    [[menu.main]]
        identifier = "solve"
        name = "Solve: Thought Leadership"
        url = "https://www.rackspace.com/solve"
        weight = 3
        parent = "blogs"
[[menu.main]]
    identifier = "support_documentation"
    name = "Support Documentation"
    url = "https://support.rackspace.com/"
    weight = 4
[[menu.buttons]]
    identifier = "buynow"
    name = "Buy Now"
    url = "#"
    weight = 5
[[menu.buttons]]
    identifier = "login"
    name = "Login"
    url = "#"
    weight = 6


[outputFormats.OpenSearch]
baseName = "opensearch"
isPlainText = true
mediaType = "application/xml"

[outputFormats.Redirects]
baseName = "redirects"
isPlainText = true
mediatype = "application/json"
notAlternative = true
[outputs]
home = ["HTML", "RSS", "OpenSearch", "Redirects"]
[params]
dateformat = "January 2, 2006"
description = "Rackspace Developer documentation using static site generator and headless CMS"
ghrepo = "https://github.com/rackerlabs/technical-blog"
ghrepo_edit = "https://github.com/rackerlabs/technical-blog/edit/master/hugo/content/"
ghrepo_new = "https://github.com/rackerlabs/technical-blog/issues/new"
images = ["/img"]
[related]
includeNewer = true
threshold = 10
toLower = true
[[related.indices]]
name = "Section"
weight = 200
[[related.indices]]
name = "keywords"
weight = 150
[[related.indices]]
name = "author"
weight = 150
[[related.indices]]
name = "categories"
weight = 150
[[related.indices]]
name = "tags"
weight = 100
[[related.indices]]
name = "date"
pattern = "2006"
weight = 10
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
