[build.environment]
  YARN_VERSION = "1.22.4"
  NPM_VERSION = "6.14.5"

[build]
  command = "make build"
  publish = "public"

[context.deploy-preview]
  command = "make build-preview"
  publish = "public"


[[redirects]]
  from = "https://docs-technical-blog.netlify.app/"
  to = "https://docs-technical-blog.netlify.app/blog/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "https://docs.rackspace.com/blog/"
  to = "https://docs-technical-blog.netlify.app/blog/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "https://docs.rackspace.com/img/*"
  to = "https://docs-technical-blog.netlify.app/img/*"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
  
[[redirects]]
  from = "https://docs.rackspace.com/blog/favicons/*"
  to = "https://docs-technical-blog.netlify.app/favicons/*"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"

